export const projects = [
    {
        id: 1,
        name: "Belahodod",
        category: "Graduation Project | Mobile & Dashboard App",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, Jira, Github, Stack Overflow, Behance, Pinterest ",
        description:
            "Graduation mobile & dashboard app with modern UI featuring smooth interactions and a clear workflow using Scrum while interactive components enhance usability and the layout remains engaging.",
        link: "https://github.com/MinaFarhat/belahdodfinal",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/BelaHodod WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Belahodod ScreenShot.png",
    },
    {
        id: 2,
        name: "ecoTransferz",
        category: "Freelance Project | Mobile & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Pinterest, Behance",
        description:
            "Designed a mobile and dashboard platform with clarity, usability, and smooth navigation while adapting to evolving client feedback to create an intuitive interface with consistent visuals and interactive elements enhancing user experience.",
        link: "https://www.behance.net/gallery/243815425/ecoTransferz-Full-UIUX-Design-Prototype",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/ecoTransferz WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/ecotransferz ScreenShot.png",
    },
    {
        id: 3,
        name: "Music App",
        category: "Personal Project | Mobile App Design",
        role: "UI/UX Designer",
        tools: "Figma, Pinterest, Behance",
        description:
            "Designed a modern music app with clean visuals and intuitive navigation focusing on smooth interactions and a user-friendly interface while creating engaging layouts to enhance the overall listening experience.",
        link: "https://www.behance.net/gallery/221293003/Music-App-design",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/Music App WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Music App ScreenShot.png",
    },
    {
        id: 4,
        name: "General Organization for Tourism and Hotels (Syria)",
        category: "Company Project | Web & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Pinterest, Behance",
        description:
            "Designed web and dashboard interfaces for the tourism and hotels authority focusing on structured content, accessibility, modern visual hierarchy, and adjusting the design to meet client feedback.",
        link: "https://www.behance.net/gallery/237275785/Website-of-the-SGA-for-Tourism-and-Hotel-Training",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/Syrian Tourism Authority WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Syrian Tourism Authority ScreenShot.png",
    },
    {
        id: 5,
        name: "MediPharma",
        category: "University Project | Mobile & Dashboard App",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, Jira, Github, Stack Overflow, Behance, Pinterest ",
        description:
            "Built a healthcare mobile and dashboard app for an e-commerce pharmacy using Agile methodology focused on smooth interactions, usability, intuitive flows, and clean interface.",
        link: "https://github.com/MinaFarhat/MEDIPHARMA",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/MEDIPHARMA WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Medipharma ScreenShot.png",
    },
    {
        id: 6,
        name: "Di-Va",
        category: "University Project | Social Media App",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, Adobe, Github, Stack Overflow, Behance, Pinterest",
        description:
            "Built a social media mobile app for university, focusing on smooth interactions, responsive UI, and seamless user experience while exploring coding and interface design.",
        link: "https://github.com/MinaFarhat/Di-Va",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/DiVa WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Diva ScreenShot.png",
    },
    {
        id: 7,
        name: "ESTRATIJIYA",
        category: "Freelance Project | Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Pinterest, Behance",
        description:
            "Designed a data-driven dashboard for a client, focusing on clear layouts, smooth interactions, and usability while adapting to feedback. Interactive elements enhanced the user experience and maintained visual consistency.",
        link: "https://www.behance.net/gallery/228033535/ESTRATIJIYA",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/ESTRATIJIYA WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/ESTRATIJIYA ScreenShot.png",
    },
    {
        id: 8,
        name: "Disabled People App",
        category: "Freelance Project | Mobile App Design",
        role: "UI/UX Designer",
        tools: "Figma, Pinterest, Behance",
        description:
            "Designed an accessible mobile app with inclusive design principles, focusing on usability, smooth interactions, and intuitive navigation. The interface adapts to user needs and enhances overall accessibility while maintaining visual clarity.",
        link: "https://www.behance.net/gallery/224126851/Disabled-Persons",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/Disabled People WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Disabled People ScreenShot.png",
    },
    {
        id: 9,
        name: "Camera Booth",
        category: "Freelance Project | Desktop & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Pinterest, Behance",
        description:
            "Designed desktop and dashboard interfaces focusing on simplicity, consistent visuals, smooth workflow, and intuitive interactions. The layout ensures clarity, efficiency, and a professional user experience across all screens.",
        link: "https://www.behance.net/gallery/237274995/Camera-Booth",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/Camera Booth WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Camera Booth ScreenShot.png",
    },
    {
        id: 10,
        name: "Roza Clinic",
        category: "Freelance Project | Mobile & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Pinterest, Behance",
        description:
            "Designed mobile and dashboard solutions for a beauty clinic focusing on intuitive navigation, smooth interactions, and efficient appointment management. The layout prioritizes user experience, clarity, and accessibility for all clients.",
        link: "https://www.behance.net/gallery/224592817/Roza-Clinic",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/Roza Clinic WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Roza Clinic ScreenShot.png",
    },
    {
        id: 11,
        name: "General Syrian Judo Federation",
        category: "Freelance Project | Web Design",
        role: "UI/UX Designer",
        tools: "Figma, Pinterest, Behance",
        description: "Designed the official website for the Syrian Judo Federation with intuitive navigation, clear structure, and modern visual hierarchy, ensuring accessibility and better experience for athletes and visitors.",
        link: "https://www.behance.net/gallery/241622741/The-Syrian-General-Authority-for-Judo",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/Syrian Judo Authority Website WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Syrian Judo Authority Website ScreenShot.png",
    },
    {
        id: 12,
        name: "Compiler Project",
        category: "University Project | Compiler Development",
        role: "Software Engineer, Java Developer",
        tools: "Java, ANTLR, Stack Overflow",
        description:
            "Built a robust compiler simulating Flutter's compiler, implementing lexical and syntax analysis, constructing AST and classes, and generating HTML, CSS, and JavaScript output, ensuring efficient and maintainable code.",
        link: "https://github.com/MinaFarhat/compiler2",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/Compiler Project WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Compiler Project ScreenShot.png",
    },
    {
        id: 13,
        name: "Operating Systems Project",
        category: "University Project | Bash Scripting",
        role: "Software Engineer, Bash Script Developer",
        tools: "Bash Script, Linux, Ubuntu, Stack Overflow",
       description: "Worked on an operating systems project focused on automation and scripting, enhancing programming skills, developing Bash scripts, and implementing solutions to manage system tasks.",
        link: "",
        image: "https://MinaFarhat.github.io/Mena-Portfolio/assets/all-projects-images/Operating Systems Project WallPaper.png",
        preview: "https://MinaFarhat.github.io/Mena-Portfolio/assets/ScreenShots/Bash Script ScreenShot.webp",
    },
];