export const projects = [
    {
        id: 1,
        name: "Belahodod",
        category: "Graduation Project | Mobile & Dashboard Application",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, GitHub",
        description: "Modern graduation mobile and dashboard app designed with a clean UI, structured workflow, optimized user experience, and scalable architecture for efficient performance.",
        link: "https://github.com/MenaFarhat/BelaHodod.git",
        image: "assets/all-projects-images/BelaHodod WallPaper.png",
        preview: "assets/ScreenShots/Belahodod ScreenShot.png",
    },
    {
        id: 2,
        name: "ecoTransferz",
        category: "Freelance Project | Mobile & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a mobile and dashboard platform focused on usability, smooth navigation, and visual consistency.",
        link: "https://www.behance.net/gallery/243815425/ecoTransferz-Full-UIUX-Design-Prototype",
        image: "assets/all-projects-images/ecoTransferz WallPaper.png",
        preview: "assets/ScreenShots/ecotransferz ScreenShot.png",
    },
    {
        id: 3,
        name: "Music App",
        category: "Personal Project | Mobile App Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a modern music app focused on intuitive navigation, smooth interactions, and a clean visual system.",
        link: "https://www.behance.net/gallery/221293003/Music-App-design",
        image: "assets/all-projects-images/Music App WallPaper.png",
        preview: "assets/ScreenShots/Music App ScreenShot.png",
    },
    {
        id: 4,
        name: "General Organization for Tourism and Hotels (Syria)",
        category: "Company Project | Web & Dashboard Platform",
        role: "UI/UX Designer",
        tools: "Figma, Wireframing",
        description: "UI/UX design for a web and dashboard platform focused on structured content, accessibility, and clear visual hierarchy.",
        link: "https://www.behance.net/gallery/237275785/Website-of-the-SGA-for-Tourism-and-Hotel-Training",
        image: "assets/all-projects-images/Syrian Tourism Authority WallPaper.png",
        preview: "assets/ScreenShots/Syrian Tourism Authority ScreenShot.png",
    },
    {
        id: 5,
        name: "MediPharma",
        category: "University Project | Mobile & Dashboard Application",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, GitHub",
        description: "Healthcare mobile and dashboard app built with Flutter for an e-commerce pharmacy focused on usability, smooth flows, and scalable architecture.",
        link: "https://github.com/MenaFarhat/MEDIPHARMA.git",
        image: "assets/all-projects-images/MEDIPHARMA WallPaper.png",
        preview: "assets/ScreenShots/Medipharma ScreenShot.png",
    },
    {
        id: 6,
        name: "Di-Va",
        category: "University Project | Social Media Application",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, GitHub, Adobe Illustrator",
        description: "Social media mobile app built with Flutter focused on responsive UI, smooth interactions, and scalable feature structure.",
        link: "https://github.com/MenaFarhat/Di-Va.git",
        image: "assets/all-projects-images/DiVa WallPaper.png",
        preview: "assets/ScreenShots/Diva ScreenShot.png",
    },
    {
        id: 7,
        name: "ESTRATIJIYA",
        category: "Freelance Project | Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Data Visualization",
        description: "UI/UX design for a data-driven dashboard focused on clear layouts, structured analytics, and smooth user interactions.",
        link: "https://www.behance.net/gallery/228033535/ESTRATIJIYA",
        image: "assets/all-projects-images/ESTRATIJIYA WallPaper.png",
        preview: "assets/ScreenShots/ESTRATIJIYA ScreenShot.png",
    },
    {
        id: 8,
        name: "Disabled People App",
        category: "Freelance Project | Mobile App Design",
        role: "UI/UX Designer",
        tools: "Figma, Accessibility Design",
        description: "UI/UX design for an accessible mobile app focused on inclusive design, adaptive interfaces, and intuitive user flows.",
        link: "https://www.behance.net/gallery/224126851/Disabled-Persons",
        image: "assets/all-projects-images/Disabled People WallPaper.png",
        preview: "assets/ScreenShots/Disabled People ScreenShot.png",
    },
    {
        id: 9,
        name: "Camera Booth",
        category: "Freelance Project | Desktop & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, User Flow Design",
        description: "UI/UX design for a desktop and dashboard system emphasizing structured layouts, workflow efficiency, and professional user experience.",
        link: "https://www.behance.net/gallery/237274995/Camera-Booth",
        image: "assets/all-projects-images/Camera Booth WallPaper.png",
        preview: "assets/ScreenShots/Camera Booth ScreenShot.png",
    },
    {
        id: 10,
        name: "Roza Clinic",
        category: "Freelance Project | Mobile & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a beauty clinic mobile and dashboard platform focused on intuitive navigation, booking workflows, and visual clarity.",
        link: "https://www.behance.net/gallery/224592817/Roza-Clinic",
        image: "assets/all-projects-images/Roza Clinic WallPaper.png",
        preview: "assets/ScreenShots/Roza Clinic ScreenShot.png",
    },
    {
        id: 11,
        name: "General Syrian Judo Federation",
        category: "Freelance Project | Web Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for the official website of the Syrian Judo Federation focused on clear structure, intuitive navigation, and modern visual hierarchy.",
        link: "https://www.behance.net/gallery/241622741/The-Syrian-General-Authority-for-Judo",
        image: "assets/all-projects-images/Syrian Judo Authority Website WallPaper.png",
        preview: "assets/ScreenShots/Syrian Judo Authority Website ScreenShot.png",
    },
    {
        id: 12,
        name: "Compiler Project",
        category: "University Project | Compiler Implementation",
        role: "Software Engineer, Java Developer",
        tools: "Java, ANTLR, HTML, CSS, JavaScript",
        description: "Custom compiler built with Java and ANTLR implementing lexical and syntax analysis, AST construction, and structured code generation.",
        link: "https://github.com/MenaFarhat/JavaCompilerProject.git",
        image: "assets/all-projects-images/Compiler Project WallPaper.png",
        preview: "assets/ScreenShots/Compiler Project ScreenShot.png",
    },
    {
        id: 13,
        name: "Operating Systems Project",
        category: "University Project | Operating Systems Automation",
        role: "Software Engineer, Bash Script Developer",
        tools: "Bash, Linux (Ubuntu)",
        description: "Developed Bash scripts for system automation and task management within a Linux operating systems environment.",
        link: "",
        image: "assets/all-projects-images/Operating Systems Project WallPaper.png",
        preview: "assets/ScreenShots/Bash Script ScreenShot.webp",
    },
];