export const projects = [
    {
        id: 1,
        name: "Bela Hodod",
        category: "Graduation Project | Mobile & Dashboard App",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, GitHub",
        description: "Modern graduation mobile and dashboard app designed with a clean UI, structured workflow, optimized user experience, and scalable architecture for efficient performance.",
        link: "https://github.com/MenaFarhat/BelaHodod.git",
        image: "assets/all-projects-images/BelaHodod WallPaper.png",
        preview: "assets/Previews/Belahodod Preview.png",
    },
    {
        id: 2,
        name: "Music App",
        category: "Personal Project | Mobile App Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a modern music app focused on intuitive navigation, smooth interactions, and a clean visual system.",
        link: "https://www.behance.net/gallery/221293003/Music-App-design",
        image: "assets/all-projects-images/Music App WallPaper.png",
        preview: "assets/Previews/Music App Preview.png",
    },
    {
        id: 3,
        name: "ecoTransferz",
        category: "Freelance Project | Mobile App & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Design System, Prototyping",
        description: "UI/UX design for a transportation and delivery platform focused on intuitive booking flows, scalable design systems, and a consistent cross-platform experience.",
        link: "https://www.behance.net/gallery/243815425/ecoTransferz-Full-UIUX-Design-Prototype",
        image: "assets/all-projects-images/ecoTransferz WallPaper.png",
        preview: "assets/Previews/ecotransferz Preview.png",
    },
    {
        id: 4,
        name: "DigiS",
        category: "Concept Project | Responsive Landing Page Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a responsive landing page focused on modern visuals, clear content hierarchy, and a seamless experience across desktop and mobile devices.",
        link: "https://www.behance.net/gallery/250444445/DigiS-Responsive-Landing-Page-Design",
        image: "assets/all-projects-images/DigiS. WallPaper.png",
        preview: "assets/Previews/DigiS. Preview.png",
    },
    {
        id: 5,
        name: "ESTRATIJIYA",
        category: "Freelance Project | Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a data-driven dashboard focused on clear layouts, structured analytics, and smooth user interactions.",
        link: "https://www.behance.net/gallery/228033535/ESTRATIJIYA",
        image: "assets/all-projects-images/ESTRATIJIYA WallPaper.png",
        preview: "assets/Previews/ESTRATIJIYA Preview.png",
    },
    {
        id: 6,
        name: "Syrian Tourism & Hotel Training Authority",
        category: "Company Project | Web & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a web and dashboard platform focused on structured content, accessibility, and clear visual hierarchy.",
        link: "https://www.behance.net/gallery/237275785/Website-of-the-SGA-for-Tourism-and-Hotel-Training",
        image: "assets/all-projects-images/Syrian Tourism Authority WallPaper.png",
        preview: "assets/Previews/Syrian Tourism Authority Preview.png",
    },
    {
        id: 7,
        name: "MediPharma",
        category: "University Project | Mobile & Dashboard App",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, GitHub",
        description: "Healthcare mobile and dashboard app built with Flutter for an e-commerce pharmacy, focused on intuitive user flows, efficient product management, and scalable architecture.",
        link: "https://github.com/MenaFarhat/MEDIPHARMA.git",
        image: "assets/all-projects-images/MEDIPHARMA WallPaper.png",
        preview: "assets/Previews/Medipharma Preview.png",
    },
    {
        id: 8,
        name: "DiVa",
        category: "University Project | Social Media App",
        role: "Flutter Developer, UI/UX Designer",
        tools: "Flutter, Figma, GitHub, Adobe Illustrator",
        description: "Social media mobile app built with Flutter focused on responsive UI, smooth interactions, and scalable feature structure.",
        link: "https://github.com/MenaFarhat/Di-Va.git",
        image: "assets/all-projects-images/DiVa WallPaper.png",
        preview: "assets/Previews/Diva Preview.png",
    },
    {
        id: 9,
        name: "Smart Search",
        category: "University Project | Search & Data Processing App",
        role: "Flutter Developer, Algorithm Engineer",
        tools: "Flutter, Jupyter Notebook, GitHub",
        description: "Flutter application implementing advanced search algorithms with dynamic filtering, efficient query processing, and optimized search performance.",
        link: "https://github.com/MenaFarhat/SmartSearch",
        image: "assets/all-projects-images/SmartSearch WallPaper.png",
        preview: "assets/Previews/SmartSearch Preview.png",
    },
    {
        id: 10,
        name: "Sense Access",
        category: "Freelance Project | Mobile App Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for an accessible mobile app focused on inclusive design, adaptive interfaces, and intuitive user flows.",
        link: "https://www.behance.net/gallery/224126851/Disabled-Persons",
        image: "assets/all-projects-images/Disabled People WallPaper.png",
        preview: "assets/Previews/Disabled People Preview.png",
    },
    {
        id: 11,
        name: "Camera Booth",
        category: "Freelance Project | Tablet & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a desktop and dashboard system emphasizing structured layouts, workflow efficiency, and professional user experience.",
        link: "https://www.behance.net/gallery/237274995/Camera-Booth",
        image: "assets/all-projects-images/Camera Booth WallPaper.png",
        preview: "assets/Previews/Camera Booth Preview.png",
    },
    {
        id: 12,
        name: "TourGuideX",
        category: "Freelance Project | Mobile App & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a mobile app and dashboard focused on tour guide training through structured learning paths, course management, and progress tracking.",
        link: "https://www.behance.net/gallery/228093301/Tourism-rehabilitation",
        image: "assets/all-projects-images/Tour Guide Qualification Platform WallPaper.png",
        preview: "assets/Previews/Tour Guide Qualification Platform Preview.png",
    },
    {
        id: 13,
        name: "Roza Clinic",
        category: "Freelance Project | Mobile App & Dashboard Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for a beauty clinic mobile and dashboard platform focused on intuitive navigation, booking workflows, and visual clarity.",
        link: "https://www.behance.net/gallery/224592817/Roza-Clinic",
        image: "assets/all-projects-images/Roza Clinic WallPaper.png",
        preview: "assets/Previews/Roza Clinic Preview.png",
    },
    {
        id: 14,
        name: "Syrian Judo Federation",
        category: "Freelance Project | Web Design",
        role: "UI/UX Designer",
        tools: "Figma, Prototyping",
        description: "UI/UX design for the official website of the Syrian Judo Federation focused on clear structure, intuitive navigation, and modern visual hierarchy.",
        link: "https://www.behance.net/gallery/241622741/The-Syrian-General-Authority-for-Judo",
        image: "assets/all-projects-images/Syrian Judo Authority Website WallPaper.png",
        preview: "assets/Previews/Syrian Judo Authority Website Preview.png",
    },
    {
        id: 15,
        name: "Java Compiler",
        category: "University Project | Compiler Implementation",
        role: "Software Engineer, Compiler Developer",
        tools: "Java, ANTLR, HTML, CSS, JavaScript",
        description: "Custom compiler built with Java and ANTLR implementing lexical and syntax analysis, AST construction, and structured code generation.",
        link: "https://github.com/MenaFarhat/JavaCompilerProject.git",
        image: "assets/all-projects-images/Compiler Project WallPaper.png",
        preview: "assets/Previews/Compiler Project Preview.png",
    },
    {
        id: 16,
        name: "Bash Automation",
        category: "University Project | Operating Systems Automation",
        role: "Software Engineer, Automation Developer",
        tools: "Bash, Linux (Ubuntu)",
        description: "Developed Bash scripts for system automation, process management, and task optimization within a Linux environment.",
        link: "",
        image: "assets/all-projects-images/Operating Systems Project WallPaper.png",
        preview: "assets/Previews/Bash Script Preview.png",
    },
];